/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MinimalRouteImport } from './routes/_minimal'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as MinimalEntrarRouteImport } from './routes/_minimal/entrar'
import { Route as MinimalRegistoRouteImport } from './routes/_minimal/registo'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellEmpresaRouteImport } from './routes/_shell/empresa'
import { Route as ShellEncomendasRouteImport } from './routes/_shell/encomendas'
import { Route as ShellInicioRouteImport } from './routes/_shell/inicio'
import { Route as ShellOrcamentoRouteImport } from './routes/_shell/orcamento'
import { Route as ShellProdutosRouteImport } from './routes/_shell/produtos'
import { Route as ContaEncomendasRouteImport } from './routes/conta_.encomendas'
import { Route as MinimalPagamentoTokenRouteImport } from './routes/_minimal/pagamento.$token'
import { Route as ShellEncomendasIdRouteImport } from './routes/_shell/encomendas_.$id'
import { Route as ShellProdutoRefRouteImport } from './routes/_shell/produto.$ref'
import { Route as ContaEncomendasIdRouteImport } from './routes/conta_.encomendas_.$id'

const MinimalRoute = MinimalRouteImport.update({
  id: '/_minimal',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const MinimalEntrarRoute = MinimalEntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => MinimalRoute,
} as any)
const MinimalRegistoRoute = MinimalRegistoRouteImport.update({
  id: '/registo',
  path: '/registo',
  getParentRoute: () => MinimalRoute,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEmpresaRoute = ShellEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEncomendasRoute = ShellEncomendasRouteImport.update({
  id: '/encomendas',
  path: '/encomendas',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInicioRoute = ShellInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOrcamentoRoute = ShellOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProdutosRoute = ShellProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => ShellRoute,
} as any)
const ContaEncomendasRoute = ContaEncomendasRouteImport.update({
  id: '/conta_/encomendas',
  path: '/conta/encomendas',
  getParentRoute: () => rootRouteImport,
} as any)
const MinimalPagamentoTokenRoute = MinimalPagamentoTokenRouteImport.update({
  id: '/pagamento/$token',
  path: '/pagamento/$token',
  getParentRoute: () => MinimalRoute,
} as any)
const ShellEncomendasIdRoute = ShellEncomendasIdRouteImport.update({
  id: '/encomendas_/$id',
  path: '/encomendas/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProdutoRefRoute = ShellProdutoRefRouteImport.update({
  id: '/produto/$ref',
  path: '/produto/$ref',
  getParentRoute: () => ShellRoute,
} as any)
const ContaEncomendasIdRoute = ContaEncomendasIdRouteImport.update({
  id: '/conta_/encomendas_/$id',
  path: '/conta/encomendas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/conta': typeof ContaRoute
  '/entrar': typeof MinimalEntrarRoute
  '/registo': typeof MinimalRegistoRoute
  '/empresa': typeof ShellEmpresaRoute
  '/encomendas': typeof ShellEncomendasRoute
  '/inicio': typeof ShellInicioRoute
  '/orcamento': typeof ShellOrcamentoRoute
  '/produtos': typeof ShellProdutosRoute
  '/conta/encomendas': typeof ContaEncomendasRoute
  '/pagamento/$token': typeof MinimalPagamentoTokenRoute
  '/encomendas/$id': typeof ShellEncomendasIdRoute
  '/produto/$ref': typeof ShellProdutoRefRoute
  '/conta/encomendas/$id': typeof ContaEncomendasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof ShellIndexRoute
  '/conta': typeof ContaRoute
  '/entrar': typeof MinimalEntrarRoute
  '/registo': typeof MinimalRegistoRoute
  '/empresa': typeof ShellEmpresaRoute
  '/encomendas': typeof ShellEncomendasRoute
  '/inicio': typeof ShellInicioRoute
  '/orcamento': typeof ShellOrcamentoRoute
  '/produtos': typeof ShellProdutosRoute
  '/conta/encomendas': typeof ContaEncomendasRoute
  '/pagamento/$token': typeof MinimalPagamentoTokenRoute
  '/encomendas/$id': typeof ShellEncomendasIdRoute
  '/produto/$ref': typeof ShellProdutoRefRoute
  '/conta/encomendas/$id': typeof ContaEncomendasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_minimal': typeof MinimalRouteWithChildren
  '/_shell': typeof ShellRouteWithChildren
  '/conta': typeof ContaRoute
  '/_minimal/entrar': typeof MinimalEntrarRoute
  '/_minimal/registo': typeof MinimalRegistoRoute
  '/_shell/empresa': typeof ShellEmpresaRoute
  '/_shell/encomendas': typeof ShellEncomendasRoute
  '/_shell/inicio': typeof ShellInicioRoute
  '/_shell/orcamento': typeof ShellOrcamentoRoute
  '/_shell/produtos': typeof ShellProdutosRoute
  '/conta_/encomendas': typeof ContaEncomendasRoute
  '/_shell/': typeof ShellIndexRoute
  '/_minimal/pagamento/$token': typeof MinimalPagamentoTokenRoute
  '/_shell/encomendas_/$id': typeof ShellEncomendasIdRoute
  '/_shell/produto/$ref': typeof ShellProdutoRefRoute
  '/conta_/encomendas_/$id': typeof ContaEncomendasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conta'
    | '/entrar'
    | '/registo'
    | '/empresa'
    | '/encomendas'
    | '/inicio'
    | '/orcamento'
    | '/produtos'
    | '/conta/encomendas'
    | '/pagamento/$token'
    | '/encomendas/$id'
    | '/produto/$ref'
    | '/conta/encomendas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conta'
    | '/entrar'
    | '/registo'
    | '/empresa'
    | '/encomendas'
    | '/inicio'
    | '/orcamento'
    | '/produtos'
    | '/conta/encomendas'
    | '/pagamento/$token'
    | '/encomendas/$id'
    | '/produto/$ref'
    | '/conta/encomendas/$id'
  id:
    | '__root__'
    | '/_minimal'
    | '/_shell'
    | '/conta'
    | '/_minimal/entrar'
    | '/_minimal/registo'
    | '/_shell/empresa'
    | '/_shell/encomendas'
    | '/_shell/inicio'
    | '/_shell/orcamento'
    | '/_shell/produtos'
    | '/conta_/encomendas'
    | '/_shell/'
    | '/_minimal/pagamento/$token'
    | '/_shell/encomendas_/$id'
    | '/_shell/produto/$ref'
    | '/conta_/encomendas_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MinimalRoute: typeof MinimalRouteWithChildren
  ShellRoute: typeof ShellRouteWithChildren
  ContaRoute: typeof ContaRoute
  ContaEncomendasRoute: typeof ContaEncomendasRoute
  ContaEncomendasIdRoute: typeof ContaEncomendasIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_minimal': {
      id: '/_minimal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MinimalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_minimal/entrar': {
      id: '/_minimal/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof MinimalEntrarRouteImport
      parentRoute: typeof MinimalRoute
    }
    '/_minimal/registo': {
      id: '/_minimal/registo'
      path: '/registo'
      fullPath: '/registo'
      preLoaderRoute: typeof MinimalRegistoRouteImport
      parentRoute: typeof MinimalRoute
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/empresa': {
      id: '/_shell/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof ShellEmpresaRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/encomendas': {
      id: '/_shell/encomendas'
      path: '/encomendas'
      fullPath: '/encomendas'
      preLoaderRoute: typeof ShellEncomendasRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/inicio': {
      id: '/_shell/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof ShellInicioRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/orcamento': {
      id: '/_shell/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof ShellOrcamentoRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/produtos': {
      id: '/_shell/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ShellProdutosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/conta_/encomendas': {
      id: '/conta_/encomendas'
      path: '/conta/encomendas'
      fullPath: '/conta/encomendas'
      preLoaderRoute: typeof ContaEncomendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_minimal/pagamento/$token': {
      id: '/_minimal/pagamento/$token'
      path: '/pagamento/$token'
      fullPath: '/pagamento/$token'
      preLoaderRoute: typeof MinimalPagamentoTokenRouteImport
      parentRoute: typeof MinimalRoute
    }
    '/_shell/encomendas_/$id': {
      id: '/_shell/encomendas_/$id'
      path: '/encomendas/$id'
      fullPath: '/encomendas/$id'
      preLoaderRoute: typeof ShellEncomendasIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/produto/$ref': {
      id: '/_shell/produto/$ref'
      path: '/produto/$ref'
      fullPath: '/produto/$ref'
      preLoaderRoute: typeof ShellProdutoRefRouteImport
      parentRoute: typeof ShellRoute
    }
    '/conta_/encomendas_/$id': {
      id: '/conta_/encomendas_/$id'
      path: '/conta/encomendas/$id'
      fullPath: '/conta/encomendas/$id'
      preLoaderRoute: typeof ContaEncomendasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MinimalRouteChildren {
  MinimalEntrarRoute: typeof MinimalEntrarRoute
  MinimalRegistoRoute: typeof MinimalRegistoRoute
  MinimalPagamentoTokenRoute: typeof MinimalPagamentoTokenRoute
}

const MinimalRouteChildren: MinimalRouteChildren = {
  MinimalEntrarRoute: MinimalEntrarRoute,
  MinimalRegistoRoute: MinimalRegistoRoute,
  MinimalPagamentoTokenRoute: MinimalPagamentoTokenRoute,
}

const MinimalRouteWithChildren =
  MinimalRoute._addFileChildren(MinimalRouteChildren)

interface ShellRouteChildren {
  ShellEmpresaRoute: typeof ShellEmpresaRoute
  ShellEncomendasRoute: typeof ShellEncomendasRoute
  ShellInicioRoute: typeof ShellInicioRoute
  ShellOrcamentoRoute: typeof ShellOrcamentoRoute
  ShellProdutosRoute: typeof ShellProdutosRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellEncomendasIdRoute: typeof ShellEncomendasIdRoute
  ShellProdutoRefRoute: typeof ShellProdutoRefRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellEmpresaRoute: ShellEmpresaRoute,
  ShellEncomendasRoute: ShellEncomendasRoute,
  ShellInicioRoute: ShellInicioRoute,
  ShellOrcamentoRoute: ShellOrcamentoRoute,
  ShellProdutosRoute: ShellProdutosRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellEncomendasIdRoute: ShellEncomendasIdRoute,
  ShellProdutoRefRoute: ShellProdutoRefRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MinimalRoute: MinimalRouteWithChildren,
  ShellRoute: ShellRouteWithChildren,
  ContaRoute: ContaRoute,
  ContaEncomendasRoute: ContaEncomendasRoute,
  ContaEncomendasIdRoute: ContaEncomendasIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
