/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as RegistoRouteImport } from './routes/registo'
import { Route as ProdutoRefRouteImport } from './routes/produto.$ref'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistoRoute = RegistoRouteImport.update({
  id: '/registo',
  path: '/registo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoRefRoute = ProdutoRefRouteImport.update({
  id: '/produto/$ref',
  path: '/produto/$ref',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/entrar': typeof EntrarRoute
  '/produtos': typeof ProdutosRoute
  '/registo': typeof RegistoRoute
  '/produto/$ref': typeof ProdutoRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/entrar': typeof EntrarRoute
  '/produtos': typeof ProdutosRoute
  '/registo': typeof RegistoRoute
  '/produto/$ref': typeof ProdutoRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/entrar': typeof EntrarRoute
  '/produtos': typeof ProdutosRoute
  '/registo': typeof RegistoRoute
  '/produto/$ref': typeof ProdutoRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/conta' | '/entrar' | '/produtos' | '/registo' | '/produto/$ref'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conta' | '/entrar' | '/produtos' | '/registo' | '/produto/$ref'
  id:
    | '__root__'
    | '/'
    | '/conta'
    | '/entrar'
    | '/produtos'
    | '/registo'
    | '/produto/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContaRoute: typeof ContaRoute
  EntrarRoute: typeof EntrarRoute
  ProdutosRoute: typeof ProdutosRoute
  RegistoRoute: typeof RegistoRoute
  ProdutoRefRoute: typeof ProdutoRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registo': {
      id: '/registo'
      path: '/registo'
      fullPath: '/registo'
      preLoaderRoute: typeof RegistoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$ref': {
      id: '/produto/$ref'
      path: '/produto/$ref'
      fullPath: '/produto/$ref'
      preLoaderRoute: typeof ProdutoRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContaRoute: ContaRoute,
  EntrarRoute: EntrarRoute,
  ProdutosRoute: ProdutosRoute,
  RegistoRoute: RegistoRoute,
  ProdutoRefRoute: ProdutoRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
